// Generated by CoffeeScript 1.7.1
(function() {
  var DOCSET_BASE, DOCSET_DOC_DIR, DOCSET_RES_DIR, fs, target, targets, _i, _len;

  fs = require('fs');

  DOCSET_BASE = "" + __dirname + "/ampersandjs.docset";

  DOCSET_RES_DIR = "" + DOCSET_BASE + "/Contents/Resources";

  DOCSET_DOC_DIR = "" + DOCSET_RES_DIR + "/Documents";

  targets = ["" + DOCSET_RES_DIR + "/docSet.dsidx", "" + DOCSET_DOC_DIR + "/index.html", "" + DOCSET_DOC_DIR + "/main.css", "" + DOCSET_DOC_DIR + "/normalize.min.css"];

  for (_i = 0, _len = targets.length; _i < _len; _i++) {
    target = targets[_i];
    fs.unlink(target, function() {});
  }

}).call(this);
